# -*- coding: utf-8 -*-
"""modelrun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dTQjYCMCrNd-C5Hzf2at22WjZXRBiVvN
"""

# load json and create model
from google.colab import files
from keras.models import model_from_json
import numpy as np
mapping='012345678BKNQRXabcdefgh'
print("Please load model architecture and model weights.")
files.upload()

json_file = open('model-architecture.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
# load weights into new model
model.load_weights("model_weights.h5")
print("Loaded model from disk")

print("Please upload all images.")
y=files.upload()
keys=(list(y.keys()))

import cv2
for i in range(0,len(keys)):

  im = cv2.imread(str(keys[i]),0)

  im=im.reshape(-1,28,28,1)/255.0
  x=model.predict(im)

  i=0


  first = np.argmax(x[0])

  #print(x,mapping)

  print(mapping[first])
